# Generated by Django 6.0.7 on 2026-08-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_blogarticle_product_views_count"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogArticle",
        ),
    ]
